spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course?characterEncoding=UTF8&autoReconnect=true
    username: root
    password: 744618026
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.course.mapper: trace